### ISSUE TITLE
Saving ALL workspaces

### ISSUE THREAD

**Issue by RushDynamic** [JonnyHaystack/i3-resurrect#108] opened 2021-12-26 20:57 UTC
**Is your feature request related to a problem? Please describe.**
It would be really cool if there was a way to save ALL the workspaces automatically when we run `i3-resurrect save --all` instead of just the current workspace, or whichever workspace you manually specify.

**Describe the solution you'd like**
Maybe a new flag to the save command `i3-resurrect save --all` that would save the layouts of all the workspaces.

**Describe alternatives you've considered**

**Additional context**
This would basically (nearly) restore your entire system to whatever state it was in before shutting down. Not sure if this is not possible in i3 or not since this seems like a pretty nifty feature but it hasn't been done yet, but it would be cool to see it happen.

Thanks for reading.

**Comment by JonnyHaystack** [comment] 2022-01-17 12:40
Duplicate of #84

**Closed by JonnyHaystack** 2022-01-17 12:40 UTC
Labels: enhancement
